import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const VERIFIER_PATH = 'checks/verify.mjs';
const GIT_DIR = '.git';
const CARGO_LOCKFILE = 'Cargo.lock';
const NPM_LOCKFILE = 'web/package-lock.json';
const WEB_NPMRC = 'web/.npmrc';
const WEB_MANIFEST = 'web/package.json';
const TOOLCHAIN_PIN = 'rust-toolchain.toml';
const NVMRC = '.nvmrc';
const REQUIRED_ENGINE = '>=22.15';
const REQUIRED_NODE = '22.15.1';
const BACKEND_CONFIG_MODULE = 'crates/server/src/config.rs';
const FRONTEND_ENV_DIR = 'web/src/env/';
const FRONTEND_CONFIG = 'web/next.config.ts';
const SERVER_ENV_MODULE = 'web/src/env/server.ts';
const GENERATED_DIR = 'web/src/generated/';
const GENERATOR_BANNER = 'auto-generated by openapi-typescript';
const CONTRACT_ARTIFACT = 'contract/openapi.json';
const DOMAIN_MANIFEST = 'crates/domain/Cargo.toml';
const HTTP_MANIFEST = 'crates/http/Cargo.toml';
const DOMAIN_DEPENDENCY_ALLOWLIST = Object.freeze(['serde', 'thiserror']);
const CLIENT_BOUNDARY_BUDGET = 5;
const FILE_LINE_CEILING = 300;
const BINARY_SCAN_BYTE_CEILING = 1024 * 1024;
const BINARY_SNIFF_BYTES = 8192;

const SECRET_PATTERNS = [
  /AKIA[0-9A-Z]{16}/,
  /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,
  /\b(?:api[_-]?key|secret|token|password)\b\s*[:=]\s*['"][^'"]{12,}['"]/i,
  /\bgh[pousr]_[A-Za-z0-9]{30,}\b/,
];

const findings = [];

function refuse(rule, site, detail) {
  findings.push(`${rule}  ${site}: ${detail}`);
}

function read(path) {
  return readFileSync(join(ROOT, path), 'utf8');
}

function gitignoreEntries() {
  return read('.gitignore')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line !== '' && !line.startsWith('#'));
}

function isScanExcluded(path, ignoreEntries) {
  if (path === VERIFIER_PATH || path === CARGO_LOCKFILE || path === NPM_LOCKFILE) {
    return true;
  }
  if (path === GIT_DIR || path.startsWith(`${GIT_DIR}/`)) {
    return true;
  }
  for (const entry of ignoreEntries) {
    if (entry.endsWith('/')) {
      const prefix = entry.slice(0, -1);
      if (path === prefix || path.endsWith(`/${prefix}`) || path.startsWith(entry) || path.includes(`/${entry}`)) {
        return true;
      }
    } else if (path === entry || path.endsWith(`/${entry}`)) {
      return true;
    }
  }
  return false;
}

function walk(directory, ignoreEntries) {
  const paths = [];
  for (const entry of readdirSync(join(ROOT, directory), { withFileTypes: true })) {
    const path = directory === '' ? entry.name : `${directory}/${entry.name}`;
    if (isScanExcluded(path, ignoreEntries)) {
      continue;
    }
    if (entry.isDirectory()) {
      paths.push(...walk(path, ignoreEntries));
    } else {
      paths.push(path);
    }
  }
  return paths;
}

const ignoreEntries = gitignoreEntries();
const tree = walk('', ignoreEntries);
const rustSources = tree.filter((path) => /^crates\/[^/]+\/src\/.+\.rs$/.test(path));
const webSources = tree.filter((path) => path.startsWith('web/src/') && /\.(?:ts|tsx)$/.test(path));

for (const path of tree) {
  const bytes = readFileSync(join(ROOT, path));
  if (bytes.length > BINARY_SCAN_BYTE_CEILING || bytes.subarray(0, BINARY_SNIFF_BYTES).includes(0)) {
    continue;
  }
  const text = bytes.toString('utf8');
  for (const pattern of SECRET_PATTERNS) {
    if (pattern.test(text)) {
      refuse('secret-scan', path, 'a key-like value is present; secrets never live in the tree');
    }
  }
}

for (const lockfile of [CARGO_LOCKFILE, NPM_LOCKFILE]) {
  if (!existsSync(join(ROOT, lockfile))) {
    refuse('lockfile-presence', lockfile, 'the lockfile must be committed');
  }
}

const npmrcLines = existsSync(join(ROOT, WEB_NPMRC))
  ? read(WEB_NPMRC).split(/\r?\n/).map((line) => line.trim())
  : [];
if (!npmrcLines.includes('ignore-scripts=true')) {
  refuse('install-script-refusal', WEB_NPMRC, 'must contain the line ignore-scripts=true');
}

if (!/^channel\s*=\s*"\d+\.\d+\.\d+"\s*$/m.test(existsSync(join(ROOT, TOOLCHAIN_PIN)) ? read(TOOLCHAIN_PIN) : '')) {
  refuse('toolchain-pin', TOOLCHAIN_PIN, 'must pin an exact rust toolchain version');
}
const webManifest = JSON.parse(read(WEB_MANIFEST));
if (webManifest.engines?.node !== REQUIRED_ENGINE) {
  refuse('toolchain-pin', `${WEB_MANIFEST}#engines`, `engines.node must be exactly '${REQUIRED_ENGINE}'`);
}
if ((existsSync(join(ROOT, NVMRC)) ? read(NVMRC).trim() : '') !== REQUIRED_NODE) {
  refuse('toolchain-pin', NVMRC, `must contain exactly ${REQUIRED_NODE}`);
}
if (typeof webManifest.packageManager !== 'string' || webManifest.packageManager === '') {
  refuse('toolchain-pin', `${WEB_MANIFEST}#packageManager`, 'packageManager must be declared');
}

for (const path of rustSources) {
  if (path === BACKEND_CONFIG_MODULE) {
    continue;
  }
  if (read(path).includes('std::env')) {
    refuse('env-site-confinement', path, `std::env is confined to ${BACKEND_CONFIG_MODULE}`);
  }
}

for (const path of webSources.concat(tree.filter((p) => p === FRONTEND_CONFIG))) {
  const insideEnvModule = path.startsWith(FRONTEND_ENV_DIR) || path === FRONTEND_CONFIG;
  const text = read(path);
  if (!insideEnvModule && text.includes('process.env')) {
    refuse('env-site-confinement', path, `process.env is confined to ${FRONTEND_ENV_DIR} and ${FRONTEND_CONFIG}`);
  }
  if (text.includes('NEXT_PUBLIC_') && !path.startsWith(FRONTEND_ENV_DIR)) {
    refuse('env-site-confinement', path, `NEXT_PUBLIC_ names are referenced only via ${FRONTEND_ENV_DIR}`);
  }
}

const serverEnvLines = read(SERVER_ENV_MODULE)
  .split('\n')
  .map((line) => line.trim())
  .filter((line) => line !== '' && !line.startsWith('//'));
if (serverEnvLines[0] !== 'import "server-only";' && serverEnvLines[0] !== "import 'server-only';") {
  refuse('server-secrecy-marker', SERVER_ENV_MODULE, 'the server env module must import the server-only guard first');
}

for (const path of rustSources) {
  const text = read(path);
  if (text.includes('$where')) {
    refuse('query-injection-refusal', path, 'the $where operator is refused');
  }
  const lines = text.split('\n');
  let depth = 0;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (depth > 0 && (/\bformat!\s*\(/.test(line) || /"\s*\+\s*/.test(line))) {
      refuse('query-injection-refusal', `${path}:${index + 1}`, 'string assembly inside a doc! block is refused; bind values instead');
    }
    if (/\bdoc!\s*\{/.test(line)) {
      depth += 1;
    }
    if (depth > 0) {
      depth += (line.match(/{/g) ?? []).length - (line.match(/}/g) ?? []).length - (/\bdoc!\s*\{/.test(line) ? 1 : 0);
      if (depth < 0) {
        depth = 0;
      }
    }
  }
}

for (const path of rustSources) {
  if (/\bCorsLayer\b|tower_http::cors/.test(read(path))) {
    refuse('same-origin-refusal', path, 'a CORS layer is refused; the rewrite is the same-origin seam');
  }
}
for (const path of tree.filter((p) => /^crates\/[^/]+\/Cargo\.toml$/.test(p))) {
  if (/\bcors\b/.test(read(path))) {
    refuse('same-origin-refusal', path, 'a cors feature is refused in backend manifests');
  }
}

function dependencyNames(manifestText) {
  const names = [];
  let inDependencies = false;
  for (const line of manifestText.split('\n')) {
    const heading = line.match(/^\s*\[(.+)\]\s*$/);
    if (heading !== null) {
      inDependencies = heading[1] === 'dependencies';
      continue;
    }
    if (inDependencies) {
      const name = line.match(/^\s*([\w-]+)\s*[.=]/);
      if (name !== null) {
        names.push(name[1]);
      }
    }
  }
  return names;
}
for (const name of dependencyNames(read(DOMAIN_MANIFEST))) {
  if (!DOMAIN_DEPENDENCY_ALLOWLIST.includes(name)) {
    refuse('layer-dependency', DOMAIN_MANIFEST, `the domain core admits only {${DOMAIN_DEPENDENCY_ALLOWLIST.join(', ')}}; found '${name}'`);
  }
}
for (const name of dependencyNames(read(HTTP_MANIFEST))) {
  if (name === 'store-mongo' || name === 'mongodb') {
    refuse('layer-dependency', HTTP_MANIFEST, 'the api boundary must not see the store adapter or the driver');
  }
}

const generatedFiles = tree.filter((path) => path.startsWith(GENERATED_DIR));
if (generatedFiles.length === 0) {
  refuse('contract-unidirection', GENERATED_DIR, 'the generated client must be committed');
}
for (const path of generatedFiles) {
  if (!read(path).includes(GENERATOR_BANNER)) {
    refuse('contract-unidirection', path, 'generated files carry the generator banner; hand-kept mirrors are banned');
  }
}
if (!existsSync(join(ROOT, CONTRACT_ARTIFACT))) {
  refuse('contract-unidirection', CONTRACT_ARTIFACT, 'the emitted contract must be committed');
}

const clientLeaves = webSources.filter((path) => /^\s*['"]use client['"]/m.test(read(path)));
if (clientLeaves.length > CLIENT_BOUNDARY_BUDGET) {
  refuse('client-boundary-budget', `web/src (${clientLeaves.length} leaves)`, `the 'use client' budget is ${CLIENT_BOUNDARY_BUDGET}`);
}

for (const path of rustSources.concat(webSources)) {
  if (path.startsWith(GENERATED_DIR)) {
    continue;
  }
  const lineCount = read(path).split('\n').length;
  if (lineCount > FILE_LINE_CEILING) {
    refuse('size-ceiling', path, `${lineCount} lines exceeds the ${FILE_LINE_CEILING}-line ceiling`);
  }
}

if (findings.length > 0) {
  for (const finding of findings) {
    console.error(finding);
  }
  process.exit(1);
}
console.log(`conventions: all 13 rules green over ${tree.length} committed files`);
